services:
  frontend:
    build:
      context: ./xray-classification-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container
    restart: always

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    restart: always
